# Generated by Django 4.0.3 on 2022-04-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collegion_Backend', '0004_dmmessage_groupmessage_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmmessage',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
