# Generated by Django 4.0.3 on 2022-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collegion_Backend', '0005_dmmessage_anonymous_groupmessage_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonymous_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
