# Generated by Django 4.0.3 on 2022-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collegion_Backend', '0006_profile_anonymous_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmmessage',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='display_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
